version: "3.7"

services:
  engine:
    image: node:12.13.0-alpine
    command: npm run dev-server
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    network_mode: "bridge"
